grpc:
  server:
    port: ${USER_SERVICE_GRPC_PORT:9090}

server:
  port: ${USER_SERVICE_REST_PORT:8087}

spring:
  datasource:
    url: jdbc:postgresql://${USER_SERVICE_DB_HOST:localhost}:5432/${USER_SERVICE_DB_NAME:userservicedb}
    username: ${USER_SERVICE_DB_USERNAME}
    password: ${USER_SERVICE_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml

salt: ${SALT}

service:
  user-activation:
    url: ${USER_SERVICE_PUBLIC_URL:http://localhost:8087}
    endpoint: /user/activateUser
