grpc:
  server:
    port: 9090

server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tgsharedb
    username: admin
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

salt: ${SALT:test}

service:
  user-activation:
    url: ${USER_SERVICE_URL:http://localhost:8087}
    endpoint: /user/activateUser
