grpc:
  server:
    port: ${USER_SERVICE_GRPC_PORT:9090}

server:
  port: ${USER_SERVICE_REST_PORT:8087}

spring:
  datasource:
    url: ${USER_SERVICE_DB_URL:jdbc:postgresql://localhost:5432/userservicedb}
    username: ${USER_SERVICE_DB_USERNAME}
    password: ${USER_SERVICE_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}

salt: ${SALT:test}

service:
  user-activation:
    url: ${USER_SERVICE_PUBLIC_URL:http://localhost:8087}
    endpoint: /user/activateUser
