server:
  port: ${NODE_PORT:8085}

user-service:
  host: ${USER_SERVICE_HOST:localhost}
  port: ${USER_SERVICE_PORT:9090}

spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
