server:
  port: ${DISPATCHER_PORT:8084}

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    url: ${TELEGRAM_BOT_URL} # static internet address for webhook

spring:
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}